### ISSUE TITLE
can't show phone number selector

### ISSUE THREAD

**Issue by mychaelgo** [googlesamples/android-credentials#18]
hi, i'm using google play services `compile 'com.google.android.gms:play-services-auth:11.0.4'` . After follow tutorial implemented here https://developers.google.com/identity/sms-retriever/overview , the phone number selector didn't come. I test it  with function `setEmailAddressIdentifierSupported(true)` works well but `setPhoneNumberIdentifierSupported` is not show the intent

**Comment by ithinkihaveacat** [comment]
Can you check whether the phone number is available to your test device? Quite a few device/SIM combinations don't make the number available. If your settings looks like the below, the phone number selector won't appear.

![cybocj1edo5](https://user-images.githubusercontent.com/51244/29130287-4b655068-7d21-11e7-98de-e75a6ca1f6a9.png)

**Comment by mychaelgo** [comment]
@ithinkihaveacat okay, my phone number status is Unknown too 👍

**Comment by ithinkihaveacat** [comment]
Oh good, yes that would cause it. I'm pretty sure the [Android Emulator](https://developer.android.com/studio/run/emulator.html) lets you set the phone number if you need it for testing.

**Comment by calvarez-ov** [comment]
Not working in the emulator for me, though I see a phone number in the settings.

Update: in fact, we found one sim card for which this worked (and and 5 sim cards which didn't work). The sample app worked with this sim card in a couple of phones.  On one of these phones, the sample app found nothing when another sim card was installed. So it looks like it really depends on the sim card.

What's odd, though, is that the app found nothing on emulators (Google or Genymotion). The emulators show the phone number in the system settings, and another app we have which reads the phone number from `TelephonyManager` works on the emulators.
