### ISSUE TITLE
Smart-lock: Click outside dialog handle bottom clicks :/

### ISSUE THREAD

**Issue by mtrakal** [googlesamples/android-credentials#19]
Make a buttons behind Dialog where you choose smart-lock saved identity (like: factory reset your phone, delete all photos, etc) and after click outside this dialog somewhere where you have some fatal button.

Diloag will dismiss, but button behind this dialog fill be forced to!!!!!!

It's useless.

Latest version of everything.

```
classpath 'com.android.tools.build:gradle:3.0.0-beta3'

classpath 'com.google.gms:google-services:3.1.0'
gradleVersion = '4.1'

// sdk and tools
    compileSdkVersion = 26
    buildToolsVersion = '26.0.1' // https://developer.android.com/studio/releases/build-tools.html
    minSdkVersion = 16
    targetSdkVersion = 26

    // google dependencies versions
    supportLibraryVersion = '26.0.2' // https://developer.android.com/topic/libraries/support-library/revisions.html
    playServicesVersion = '11.2.0' // https://developers.google.com/android/guides/releases
```

Video with weird behaviour here: https://youtu.be/CpJyR-xm4_M

**Comment by dxslly** [comment]
Hey @mtrakal,

Thanks for the feedback. A change preventing taps outside this dialog from being passed to windows below is already in the pipeline and is coming in future Google Play Services release. Note this will be an automatic update and does not require any changes to your app. If you would like to change this behavior immediately one option would be to intercept these touches and turn them into NoOps.

Cheers,
David

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
