### ISSUE TITLE
BroadCastReceiver not getting fired  

### ISSUE THREAD

**Issue by ankitPagalGuy** [googlesamples/android-credentials#20]
By using AppSignature class I got hash key `IV2kdanxlm6` , SMS content is `Your unique Prepathon verification code is 7357. Happy Learning, Team Prepathon. IV2kdanxlm6` Still BroadCastReceiver  is not getting fired . I have followed all the steps as shown here https://android-developers.googleblog.com/2017/10/effective-phone-number-verification.html .  Am I doing anything wrong ?

**Comment by ithinkihaveacat** [comment]
Does the message also start with `<#>`?

**Comment by ankitPagalGuy** [comment]
`Two consecutive zero-width space characters (U+200B)` ,  as mentioned in docs, I am using this , it should work ?

**Comment by ankitPagalGuy** [comment]
worked with <#>

**Comment by ithinkihaveacat** [comment]
Glad that worked, thanks for confirming! The zero-width characters should also work, but they seem vulnerable to getting dropped along the way.

**Comment by ankitPagalGuy** [comment]
@ithinkihaveacat  , I have another issue https://github.com/googlesamples/android-credentials/issues/21 , please look into this

**Comment by sumeet-chaayos** [comment]
@ankitPagalGuy @ithinkihaveacat @keyboardsurfer  Sms is not getting broadcasted , when i manually broadcast the intent from adb and its receiving in broadcast receiver. Sms is :

>  **<#> Your Verification Code is 030787. This OTP will s. NKsG/pQa+dw**


 Need urgent help here.

**Comment by vivekpanchal** [comment]
hey @sumeet-chaayos I am facing the exact problem like you.  if you find the solution please share it with me .
