### ISSUE TITLE
Having trouble in SmsRetriever

### ISSUE THREAD

**Issue by ankitPagalGuy** [googlesamples/android-credentials#21]
when first time , I insert phone no  and wait for SMS , it does not auto fill the OTP 
here is log -
`11-07 19:36:44.683 2143-2143/? I/SmsRetriever: [SmsRetrieverApiChimeraService] Prefix does not match
11-07 19:36:44.683 2143-2143/? I/SmsRetriever: [EndsWithStringMatcher] Found a match
11-07 19:36:44.683 2143-2143/? I/SmsRetriever: [SmsRetrieverApiChimeraService] No matching message is found`

But if go back and again fill the phone no , it fills the OTP
here is log -
`11-07 19:38:43.314 2143-2143/? I/SmsRetriever: [EndsWithStringMatcher] Found a match
11-07 19:38:43.314 2143-2143/? I/SmsRetriever: [SmsRetrieverApiChimeraService] Matched prefix:[#]`

Have tried debugging but can't find anything

**Comment by ithinkihaveacat** [comment]
Not quite sure what could be causing this :-(.

Can you get [the sample app](https://github.com/googlesamples/android-credentials/tree/master/sms-verification/android) to work? (For testing purposes you should be able to send text messages "manually" via `adb` or the emulator, rather than setting up the service.)

**Comment by LOG-TAG** [comment]
@ithinkihaveacat I just want to know is the sample code updated to details explained in this video? https://www.youtube.com/watch?v=jzWYv8y2v1c

**Comment by ithinkihaveacat** [comment]
@LOG-TAG Yes, the sample code should match the video.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
