### ISSUE TITLE
Begin the SMS with two consecutive zero-width space characters (U+200B) doesn't work

### ISSUE THREAD

**Issue by gabrieldelmas** [googlesamples/android-credentials#23]
Hello,

I use the Google Play services (version 11.4.0), I'm able to send a SMS and retrieve the message by the BroadcastReceiver (as in your example "SMS Verify App") if the SMS message begins with "<#>".

Unfortunately, if I replace "<#>" by two consecutive zero-width space characters, my BroadcastReceiver is not called and I finally received a callback 5min later for a timeout. I use this format, "\u200b\u200b", to write these two characters in unicode with my server (Java).

I wonder if it's a bug or if I miss something...

Gabriel

**Comment by samtstern** [comment]
@gabrieldelmas thanks for reporting this. Can you explain why you want to start the SMS with those characters?  It would help me understand the issue better.

**Comment by gabrieldelmas** [comment]
Thanks for taking the time to answer me. Basically, I don't want to start the SMS with "<#>" just because the SMS looks better without. The documentation seems let the choice between "<#>" or two consecutive zero-width space characters (U+200B) to begin the SMS.
https://developers.google.com/identity/sms-retriever/verify

**Comment by samtstern** [comment]
@gabrieldelmas gotcha, I actually hadn't read that bit of the documentation before!  Can you paste here the Java code you use to generate the SMS with the unicode characters?

**Comment by gabrieldelmas** [comment]
No worries. Sure, here it is :
`String body = "\u200b\u200b"  + " " + message + "\n\n" + getAndroidAppHash();
`

If I replace "\u200b\u200b" by "<#>" everything works well.

**Comment by samtstern** [comment]
@gabrieldelmas I've filed this with some backend engineers, will let you know what they have to say.

**Comment by gabrieldelmas** [comment]
@samtstern Thanks

**Comment by samtstern** [comment]
@gabrieldelmas apparently we've seen other reports like this.  We suspect it's a carrier issue, some do not properly deliver the messages with the unicode prefix.

For max reliability I'd stick with the visible prefix.  We're going to see what we can do to fix it or improve the docs.

**Comment by gabrieldelmas** [comment]
@samtstern Could make sens. Fortunately, this issue happened on my phone otherwise it would have been harder to figure out from one of our feedback's user. I will stick with the visible prefix. Thanks.

**Comment by samtstern** [comment]
Closing this for now as there's nothing we can do in this repo, but will come back if we have any more news.
