### ISSUE TITLE
App minimize on choosing the phone number from the pop-up

### ISSUE THREAD

**Issue by minion06** [googlesamples/android-credentials#25]
In some mobiles after choosing the number from popup app minimizes and i could not track what actually causes it, since the app doesn't crash it minimizes/closed. Help me to figure out the issue. The device that causes the problems are infocus and few other devices. Note: i m checking for google play services updated and request for phone number hint(using hint request from sms-verification sample).

**Comment by ithinkihaveacat** [comment]
That … seems odd. Is there a specific app that triggers this behavior? Can you attach a video showing what  happens?

**Comment by minion06** [comment]
The issue has been resolved. The problem is i have added noHistory:true to the activity in my manifest and in mobile phones running marshmallow closes the app after system pop up rises and on selecting mobile number nothing happens. It has been resolved after removing nohistory from manifest.

**Comment by ithinkihaveacat** [comment]
👍 Glad you got it sorted and thanks for following up!
