### ISSUE TITLE
Sms onReceive not getting triggered on Nexus 5.

### ISSUE THREAD

**Issue by amalChandran** [googlesamples/android-credentials#28]
Device name: Nexus 5, LG
OS: 6.0.1
Android runtime: ART 2.1.0
Google play version: 12685022(Not able to update this on this phone)
--

I tested my implementation on the above device. It successfully starts the retriever, but I never receive any broadcast in the onReceive even after I receive the SMS.

 I tried apps like Uber, etc that are using this feature on the same phone, none worked.

 However, on other devices, my implementation worked as expected. On these other phones, the version of google play services is 12685025.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
