### ISSUE TITLE
Share credentials among two apps

### ISSUE THREAD

**Issue by BulatMukhutdinov** [googlesamples/android-credentials#33]
Is it possible to share saved credentials with the second app? I have one app installed. User logins using email and password. Then when installing the second app I want to have access to this credentials

**Comment by sso-google** [comment]
Yes, if you list multiple apps within the asset linking file, credentials will be shared across them: https://stackoverflow.com/a/43128620/5001016

Documented here: https://developers.google.com/identity/smartlock-passwords/android/associate-apps-and-sites#example_associate_multiple_apps_with_a_website
