### ISSUE TITLE
Broadcast not getting fired at all.

### ISSUE THREAD

**Issue by sumeet-chaayos** [googlesamples/android-credentials#34]
@ankitPagalGuy @ithinkihaveacat @keyboardsurfer Sms is not getting broadcasted , when i manually broadcast the intent from adb and its receiving in broadcast receiver. Sms is :

> **<#> Your Verification Code is 030787. This OTP will s. NKsG/pQa+dw**

Need urgent help here.

**Comment by vedasLabs** [comment]
Have u founded any solution??
i m also getting the same error

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
