### ISSUE TITLE
Missing LICENSE file for sms-verification example app

### ISSUE THREAD

**Issue by rockebee** [googlesamples/android-credentials#35]
From legal perspective it seems that a proper LICENSE file is missing for the sms-verification examples - would it be possible to add one, so that it is also clear that example code snippets can be used without limitations on other apps?

**Comment by samtstern** [comment]
Thanks for noticing!  Added Apache 2.0 LICENSE:
https://github.com/googlesamples/android-credentials/blob/master/LICENSE
