### ISSUE TITLE
 SMS Retriever API auto fetch issue

### ISSUE THREAD

**Issue by AtifAbbAsi19** [googlesamples/android-credentials#36]
[SMS Verification with SMS Retriever API auto fetch issue](https://stackoverflow.com/questions/55216363/sms-verification-with-sms-retriever-api-auto-fetch-issue)

I'm trying to use Google's SMS Retriever API for Automatic SMS Verification, but there is an issue in it. previously , I was reading sender number using getOriginatingAddress() and if it's valid sender number then read OTP otherwise it should not read msg. As , forwarded OTP is disturbing user's privacy.

I have the following scenario.

My app is auto-fetching forwarded OTP messages.

 User A installs app on his mobile and enters User B mobile number.
 User B receives OTP and forwards it to User A.
App reads OTP on User A mobile and goes to home screen.
is there any way around to get sender number?

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
