### ISSUE TITLE
Doesn't work properly with Don't Keep Activities mode

### ISSUE THREAD

**Issue by Nublo** [googlesamples/android-credentials#39]
**Steps to reproduce**

- Set Don't keep activities flag
- Open app -> You will see email dialog
- Fold the app
- Unfold
- Tap on the dialog with any email

**Result**
In the form you will see(label with email field), that you are still signOut.

**Expected result**
You will be signedIn(correct email is shown).

**Addition**
If after this steps you will fold/unfold application one more time you will be signedIn. 
As expected.

I investigated a little bit, and looks like we are not receiving onActivityResult after first fold/unfold, but receive after second, which is super strange.

**Comment by codingjeremy** [comment]
I am closing this issue/PR, as it has been migrated to the new repo linked above in the comments. Thank you!
