### ISSUE TITLE
statusCode=DEVELOPER_ERROR

### ISSUE THREAD

**Issue by SoumyajitPal** [googlesamples/android-credentials#7]
/com.google.example.credentialssignin D/MainActivity: handleGoogleSignIn:Status{statusCode=DEVELOPER_ERROR, resolution=null}

I get this error in my LogCat after trying to sign in through the sample app credentials-signin
Am I missing something?

**Comment by samtstern** [comment]
@SoumyajitPal make sure you have your Client IDs set up in the console, paying particular attention to the SHA1 and package name.

**Comment by SoumyajitPal** [comment]
@samtstern  Thanks for your response and sorry for the late reply, but I couldn't find any such place where I can provide client ID and SHA1/SHA512 in the credentials-signin app. I've used them in the credentials-quickstart app though. So can you please be a little more specific? I'm a newbie

**Comment by samtstern** [comment]
@SoumyajitPal no problem.  Visit developers.google.com/mobile/add to set up this information.  When asked for a package name use the package name of the sample app (`com.google.example.credentialssignin`) and when asked for a SHA1 follow the instructions to get this information from your own machine.

**Comment by SoumyajitPal** [comment]
@samtstern That worked. Thank you!
